[ ButtonMapping   ]    # this is a comment
# See `xwiimote-mouse-bridge -k` to generate a list of possible key codes to use here.
# BTN_LEFT and BTN_RIGHT are mouse buttons.
# The special value '%SCROLL' may be used to specify a key to activate scrolling.

B =     BTN_LEFT   
A =     KEY_SPACE     
    
Home =  KEY_LEFTMETA
Minus = KEY_VOLUMEDOWN
Plus =  KEY_VOLUMEUP  
Up =    KEY_UP
Down =  KEY_DOWN
Left =  KEY_LEFT
Right = KEY_RIGHT
1 =     %SCROLL
2 =     BTN_RIGHT

[Options]
# Prevent the cursor from moving for a short time after pressing a mouse button on the remote.
# This may make precise clicking easier. Set to 0 to disable it.
MouseLockDelay = 250 # ms

AngVelThreshold = 162
SubpixelsPerScreenPixel = 500

# Regular expressions used to match the Wii Remote when it connects.
WiimoteDeviceName = ^Nintendo Wii Remote$
MotionPlusDeviceName  = ^Nintendo Wii Remote Motion Plus$

[Adjustment]
# Apply a constant offset to the gyroscope data to prevent unwanted motion.
# The "Z" axis of the Wii Remote gyroscope corresponds to the "Y" (up and down) axis for the mouse.
# +/- Wiimote motion units 
 OffsetX = -100
 OffsetY = -500
 InvertX = false
 InvertY = true

#OffsetX = -1473
#OffsetY = 1152
#InvertX = true
#InvertY = false

#[Scale]
# Adjust the sensitivity and/or invert the movement direction.
# +/- Wiimote motion units per pixel of cursor movement
#X =  300
#Y = -300

# Adjust the scrolling sensitivity and/or invert the scrolling direction.
# High-resolution scrolling is used, so this value is multiplied by 120 internally.
# +/- Wiimote motion units per "click", or "detent", of the virtual mouse wheel
#Scroll = 166
